### ISSUE TITLE
Crear lightcurve step

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/lightcurve-step#1]
```[tasklist]
### Tasks
- [x] Crear estructura básica que consuma mensajes de correction-step
- [x] Crear conexión a BD que obtiene la curva de luz con todas las detecciones y no detecciones
- [x] Producir mensaje de salida con curva de luz completa (una por aid)
```

# Criterio de aceptación
- Funciona por batches
- Consume mensajes desde correction step
- Produce mensaje con curva de luz que incluye detecciones, no detecciones y aid
- Funciona para ZTF y ATLAS
- Si la BD está indexada por candid (_id==candid), usar _id para comparar con las detecciones del stream. Si el campo candid existe, usar candid.
